In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3],type(np.array([1,2,3])))

In [6]:
np.array([1,2,3,"hello"])

array(['1', '2', '3', 'hello'], dtype='<U21')

In [7]:
array = np.array([1,2,3])
array, array.dtype

(array([1, 2, 3]), dtype('int64'))

In [8]:
array = np.array([1,2,3],dtype = np.int8)
array, array.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [9]:
2**8



256

In [10]:
2**8-1

255

In [11]:
bin(2**8)

'0b100000000'

In [12]:
bin(2**8-1)

'0b11111111'

In [16]:
array = np.array([1,2,3,127,-128], dtype = np.int8)
array

array([   1,    2,    3,  127, -128], dtype=int8)

In [21]:
array = np.array([1,2,3,127,255], dtype = np.uint8)
array

array([  1,   2,   3, 127, 255], dtype=uint8)